name: Build and release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        include:
          - python: python3
            pip: pip3
          - python: python2
            pip: pip
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}
          fetch-depth: 0

      - name: Install python dependencies
        run: |
          ${{ matrix.pip }} install --user --upgrade pip
          ${{ matrix.pip }} --no-cache-dir install --user setuptools wheel "urllib3==1.25.11"
          ${{ matrix.pip }} --no-cache-dir install --user -e .[tests,docs]

      - name: Show python dependencies
        run: |
          ${{ matrix.python }} --version
          ${{ matrix.pip }} freeze

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Run tests
        run: |
          ./run-tests.sh

      - name: Build package
        if: ${{ success() && github.event_name == 'push' && matrix.python == 'python2'  }}
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package
        if: ${{ success() && github.event_name == 'push' && matrix.python == 'python2'  }}
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}

