name: Pull request master

on:
  pull_request:
    branches: [master]

jobs:
  python2_tests:
    uses: ./.github/workflows/test-python-2.yml

  python311_tests:
    uses: ./.github/workflows/test-python-311.yml

  python312_tests:
    uses: ./.github/workflows/test-python-312-313.yml
