name: Build and release

on:
  push:
    branches: [master]

jobs:
  python2_tests:
    uses: ./.github/workflows/test-python-2.yml

  python311_tests:
    uses: ./.github/workflows/test-python-311.yml

  python312_tests:
    uses: ./.github/workflows/test-python-312-313.yml

  bump_version:
    needs: [python2_tests, python311_tests, python312_tests]
    uses: ./.github/workflows/bump-and-publish.yml
    secrets: inherit
