name: Test Python 2

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python: python2
            pip: pip
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install -y python2

      - name: Lint - Pre-commit check
        uses: pre-commit/action@v3.0.1

      - name: Install python dependencies
        run: |
          wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
          ${{ matrix.python }} get-pip.py
          ${{ matrix.python }} -m ${{ matrix.pip }} install --user --upgrade pip
          ${{ matrix.python }} -m ${{ matrix.pip }} install --upgrade pip
          ${{ matrix.python }} -m ${{ matrix.pip }} install poetry
          rm poetry.lock
          ${{ matrix.python }} -m poetry lock
          ${{ matrix.python }} -m poetry install --no-root
      - name: Show python dependencies
        run: |
          ${{matrix.pip}} --version
          ${{ matrix.python }} --version
          ${{ matrix.pip }} freeze

      - name: Run tests
        run: |
          ./run-tests.sh
