name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: '3.12'
            allow-failure: true
          - python: '3.13'
            allow-failure: true
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint - Pre-commit check
        uses: pre-commit/action@v3.0.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with dev
      - name: Show python dependencies
        run: |
          pip --version
          python --version
          pip freeze

      - name: Run tests
        run: |
          ./run-tests.sh
